#!/bin/bash
# ============================================
# ClaraVerse One-Line Installer
# ============================================
# Usage: curl -fsSL https://raw.githubusercontent.com/yourusername/ClaraVerse-Scarlet-OSS/main/install.sh | bash
#
# This script:
#   1. Creates a claraverse directory
#   2. Downloads docker-compose.prod.yml
#   3. Generates secure encryption keys
#   4. Starts all services
# ============================================

set -e

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m'

REPO_URL="https://raw.githubusercontent.com/yourusername/ClaraVerse-Scarlet-OSS/main"

echo ""
echo -e "${BLUE}╔════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║     🚀 ClaraVerse Installer            ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════╝${NC}"
echo ""

# Check Docker
if ! command -v docker &> /dev/null; then
    echo -e "${RED}❌ Docker not found${NC}"
    echo "Please install Docker: https://docs.docker.com/get-docker/"
    exit 1
fi

if ! docker compose version &> /dev/null 2>&1; then
    echo -e "${RED}❌ Docker Compose not found${NC}"
    echo "Please install Docker Compose: https://docs.docker.com/compose/install/"
    exit 1
fi

echo -e "${GREEN}✅ Docker is installed${NC}"

# Create directory
INSTALL_DIR="${CLARAVERSE_DIR:-claraverse}"
echo -e "${BLUE}📁 Creating directory: $INSTALL_DIR${NC}"
mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"

# Download docker-compose
echo -e "${BLUE}📥 Downloading docker-compose.yml...${NC}"
curl -fsSL "$REPO_URL/docker-compose.prod.yml" -o docker-compose.yml

# Generate .env with secure keys
if [ ! -f .env ]; then
    echo -e "${BLUE}🔑 Generating secure keys...${NC}"

    # Generate keys
    if command -v openssl &> /dev/null; then
        ENCRYPTION_KEY=$(openssl rand -hex 32)
        JWT_SECRET=$(openssl rand -hex 64)
    else
        ENCRYPTION_KEY=$(head -c 32 /dev/urandom | xxd -p -c 32 2>/dev/null || cat /dev/urandom | tr -dc 'a-f0-9' | head -c 64)
        JWT_SECRET=$(head -c 64 /dev/urandom | xxd -p -c 64 2>/dev/null || cat /dev/urandom | tr -dc 'a-f0-9' | head -c 128)
    fi

    cat > .env << EOF
# ClaraVerse Configuration
# Auto-generated by install.sh

# Security Keys (auto-generated - keep these secret!)
ENCRYPTION_MASTER_KEY=$ENCRYPTION_KEY
JWT_SECRET=$JWT_SECRET

# Environment
ENVIRONMENT=development

# URLs
FRONTEND_URL=http://localhost:80
BACKEND_URL=http://localhost:3001
ALLOWED_ORIGINS=http://localhost,http://localhost:80

# Database passwords
MYSQL_ROOT_PASSWORD=claraverse_root_2024
MYSQL_PASSWORD=claraverse_pass_2024

# E2B Local Mode (no API key needed)
E2B_MODE=local
E2B_LOCAL_USE_DOCKER=true

# JWT Settings
JWT_ACCESS_TOKEN_EXPIRY=15m
JWT_REFRESH_TOKEN_EXPIRY=168h

# Dev key (only works in development mode)
DEV_API_KEY=claraverse-dev-key-2024
EOF

    echo -e "${GREEN}✅ Configuration created${NC}"
else
    echo -e "${YELLOW}⚠️  .env already exists, keeping existing configuration${NC}"
fi

# Start services
echo ""
echo -e "${BLUE}🚀 Starting ClaraVerse...${NC}"
echo -e "${YELLOW}   This may take a few minutes on first run (downloading images)...${NC}"
echo ""

docker compose pull
docker compose up -d

# Wait for services
echo ""
echo -e "${BLUE}⏳ Waiting for services to become healthy...${NC}"

MAX_WAIT=180
ELAPSED=0
while [ $ELAPSED -lt $MAX_WAIT ]; do
    # Check if backend is healthy
    if curl -s http://localhost:3001/health 2>/dev/null | grep -q "healthy"; then
        break
    fi
    sleep 5
    ELAPSED=$((ELAPSED + 5))
    echo -ne "\r   Waiting... ${ELAPSED}s"
done

echo ""
echo ""

# Check final status
if curl -s http://localhost:3001/health 2>/dev/null | grep -q "healthy"; then
    echo -e "${GREEN}╔════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║     🎉 ClaraVerse is Running!          ║${NC}"
    echo -e "${GREEN}╚════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "  ${BLUE}Frontend:${NC}     http://localhost:80"
    echo -e "  ${BLUE}Backend API:${NC}  http://localhost:3001"
    echo ""
    echo -e "  ${YELLOW}First Steps:${NC}"
    echo "    1. Open http://localhost:80 in your browser"
    echo "    2. Register your account (first user = admin!)"
    echo "    3. Add your AI provider API keys in Settings"
    echo ""
    echo -e "  ${YELLOW}Commands:${NC}"
    echo "    Stop:    cd $INSTALL_DIR && docker compose down"
    echo "    Start:   cd $INSTALL_DIR && docker compose up -d"
    echo "    Logs:    cd $INSTALL_DIR && docker compose logs -f"
    echo "    Update:  cd $INSTALL_DIR && docker compose pull && docker compose up -d"
    echo ""
else
    echo -e "${YELLOW}⚠️  Services are still starting...${NC}"
    echo "Check status with: cd $INSTALL_DIR && docker compose ps"
    echo "View logs with: cd $INSTALL_DIR && docker compose logs -f"
fi
